name: Build
# From now in android
# https://github.com/android/nowinandroid

on:
    push:
        branches:
            - main
    pull_request:
concurrency:
    group: build-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 60

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1

            - name: Copy CI gradle.properties
              run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v3

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: "3.0"
                  bundler-cache: true

            - name: Check spotless
              run: ./gradlew spotlessCheck --stacktrace

            - name: Check lint
              run: ./gradlew lintDebug --stacktrace

            - name: Build all build type and flavor permutations
              run: ./gradlew assemble --stacktrace

            - name: Run local tests
              run: ./gradlew testDebug --stacktrace

            - name: Danger
              uses: MeilCli/danger-action@v5
              if: always()
              with:
                  plugins_file: "Gemfile"
                  install_path: "vendor/bundle"
                  danger_file: "Dangerfile"
                  danger_id: "danger-pr"
              env:
                  DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload build outputs (APKs)
              uses: actions/upload-artifact@v3
              with:
                  name: build-outputs
                  path: app/build/outputs

            - name: Upload build reports
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: build-reports
                  path: app/build/reports

    androidTest:
        needs: build
        runs-on: macOS-latest # enables hardware acceleration in the virtual machine
        timeout-minutes: 45
        strategy:
            matrix:
                api-level: [24, 29]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Copy CI gradle.properties
              run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 17

            - name: Setup Gradle
              uses: gradle/gradle-build-action@v3

            - name: Run instrumentation tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: ${{ matrix.api-level }}
                  arch: x86_64
                  emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  disable-animations: true
                  disk-size: 1500M
                  heap-size: 512M
                  script: ./gradlew connectedDebugAndroidTest

            - name: Upload test reports
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: test-reports
                  path: "*/build/reports/androidTests"
